/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import java.util.Scanner;

public class App {
    public static void main(String[] args){

        Scanner teclado = new Scanner(System.in);
        String nome;
        int v;
        int total;

        if(args.length == 0){
            nome = "World!";
        } else {
            nome = args[0];
        }

        System.out.println("Pegue uma moeda do bolso e diga o valor da moeda");

        v = teclado.nextInt();
        if (v > 0){
            total = i + v;
        }

    }


}
